name: unDeploy LSHworkspace-Maintenace Github Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  undeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create empty directory
        run: mkdir empty-dir

      - name: Deploy empty directory to remove GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          path: empty-dir